"""Add Bitbucket integration fields to users

Revision ID: 0f5023eaa6d9
Revises: add_google_oauth_fields
Create Date: 2025-09-03 17:08:14.165766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5023eaa6d9'
down_revision: Union[str, None] = 'add_google_oauth_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ai_analysis_requests', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ai_feedback', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ai_recommendations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'ai_usage_metrics', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'chat_messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'repositories', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('bitbucket_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bitbucket_username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bitbucket_user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bitbucket_user_id')
    op.drop_column('users', 'bitbucket_username')
    op.drop_column('users', 'bitbucket_access_token')
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'ai_usage_metrics', type_='foreignkey')
    op.drop_constraint(None, 'ai_recommendations', type_='foreignkey')
    op.drop_constraint(None, 'ai_feedback', type_='foreignkey')
    op.drop_constraint(None, 'ai_analysis_requests', type_='foreignkey')
    # ### end Alembic commands ###
