"""Add GitLab fields to User

Revision ID: 10422572eb62
Revises: 4f4ec4f412ce
Create Date: 2025-08-08 23:08:39.023481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10422572eb62'
down_revision: Union[str, None] = '4f4ec4f412ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
