"""add scan_metadata column

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '21aa09fdad18'
down_revision = None  # Change this to the actual previous revision if you have one
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('scan_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'scan_metadata')
    # ### end Alembic commands ###