"""Update repository model for multiple git providers

Revision ID: 6029f7da3616
Revises: 0f5023eaa6d9
Create Date: 2025-09-03 17:13:05.886651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6029f7da3616'
down_revision: Union[str, None] = '0f5023eaa6d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
