import React, { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate, useLocation } from 'react-router-dom';
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { DiffEditor, Editor } from '@monaco-editor/react';
import {
  ArrowLeft,
  Sparkles,
  AlertCircle,
  GitPullRequest,
  X,
  ChevronRight,
  FileCode2,
  CheckCircle,
  Lock,
  Check,
  XCircle
} from 'lucide-react';

interface Vulnerability {
  id: number;
  title: string;
  description: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  line_number: number | null;
  recommendation: string;
  fix_suggestion?: string;
}

const FileEditor: React.FC = () => {
  const { repositoryId } = useParams<{ repositoryId: string }>();
  const location = useLocation();
  const navigate = useNavigate();

  const rawFilePath = location.pathname.split('/files/')[1]?.replace('/edit', '') || '';
  let cleanPath = rawFilePath;
  try {
    cleanPath = decodeURIComponent(decodeURIComponent(rawFilePath));
  } catch (e) {
    try { cleanPath = decodeURIComponent(rawFilePath); } catch (e) {}
  }
  
  const pathParts = cleanPath.split('/');
  const fileName = pathParts.pop() || '';
  
  const [originalContent, setOriginalContent] = useState('');
  const [modifiedContent, setModifiedContent] = useState('');
  const [vulnerabilities, setVulnerabilities] = useState<Vulnerability[]>([]);
  const [loading, setLoading] = useState(true);
  const [language, setLanguage] = useState('javascript');
  
  const [fixingState, setFixingState] = useState<'idle' | 'all' | number>('idle');
  const [showDiff, setShowDiff] = useState(false);
  
  const [isReviewingAI, setIsReviewingAI] = useState(false);
  const [preAIFixContent, setPreAIFixContent] = useState('');
  
  const editorRef = useRef<any>(null);
  const diffEditorRef = useRef<any>(null);

  // ✅ Refs to keep Monaco callbacks perfectly synced with React State
  const vulnerabilitiesRef = useRef(vulnerabilities);
  const handleGetAISuggestionRef = useRef<any>(null);

  const [showPRDrawer, setShowPRDrawer] = useState(false);
  const [prTitle, setPrTitle] = useState(`Fix security vulnerabilities in ${fileName}`);
  const [prDescription, setPrDescription] = useState('Automated security fix generated by SecureThread.');
  const [isSubmittingPR, setIsSubmittingPR] = useState(false);
  const [prSuccessUrl, setPrSuccessUrl] = useState<string | null>(null);

  const [missingTokenError, setMissingTokenError] = useState<string | null>(null);

  useEffect(() => {
    fetchFileData();
  }, [repositoryId, rawFilePath]);

  // Keep refs updated for Monaco
  useEffect(() => {
    vulnerabilitiesRef.current = vulnerabilities;
    handleGetAISuggestionRef.current = handleGetAISuggestion;
  });

  const fetchFileData = async () => {
    try {
      const token = localStorage.getItem('access_token');
      
      const fileResponse = await fetch(
        `${import.meta.env.VITE_API_URL}/api/v1/repositories/${repositoryId}/file?file_path=${encodeURIComponent(rawFilePath)}`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      
      if (!fileResponse.ok) {
        const errData = await fileResponse.json().catch(() => null);
        const errMsg = errData?.detail || 'Failed to fetch file';
        
        if (errMsg.toLowerCase().includes('token not found')) {
          setMissingTokenError(errMsg);
          setLoading(false);
          return;
        }
        throw new Error(errMsg);
      }

      const fileData = await fileResponse.json();
      
      let content = '';
      if (typeof fileData === 'string') content = fileData;
      else if (fileData.content) {
        if (typeof fileData.content === 'string') {
          if (fileData.encoding === 'base64' || fileData.content.match(/^[A-Za-z0-9+/=]+$/)) {
            try { content = atob(fileData.content.replace(/\n/g, '')); } 
            catch (e) { content = fileData.content; }
          } else content = fileData.content;
        } else if (typeof fileData.content === 'object' && fileData.content.content) {
          try { content = atob(fileData.content.content.replace(/\n/g, '')); } 
          catch (e) { content = fileData.content.content; }
        }
      } else content = '// No content available';
      
      setOriginalContent(content);
      setModifiedContent(content);
      
      const ext = fileName.split('.').pop()?.toLowerCase() || 'javascript';
      setLanguage(getLanguageFromExtension(ext));
      
      const vulnResponse = await fetch(
        `${import.meta.env.VITE_API_URL}/api/v1/repositories/${repositoryId}/vulnerabilities?file_path=${encodeURIComponent(rawFilePath)}`,
        { headers: { Authorization: `Bearer ${token}` } }
      );
      
      if (vulnResponse.ok) {
        const vulnData = await vulnResponse.json();
        setVulnerabilities(Array.isArray(vulnData) ? vulnData : []);
      }
      setLoading(false);
    } catch (error) {
      console.error('Error fetching file data:', error);
      setOriginalContent('// Error loading file content');
      setLoading(false);
    }
  };

  const getLanguageFromExtension = (ext: string): string => {
    const map: Record<string, string> = {
      'js': 'javascript', 'jsx': 'javascript', 'ts': 'typescript', 'tsx': 'typescript',
      'py': 'python', 'java': 'java', 'php': 'php', 'rb': 'ruby', 'go': 'go',
      'rs': 'rust', 'cpp': 'cpp', 'c': 'c', 'html': 'html', 'css': 'css',
      'json': 'json', 'yaml': 'yaml', 'yml': 'yaml', 'xml': 'xml'
    };
    return map[ext] || 'javascript';
  };

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'critical': return { bg: 'bg-red-500/20', border: 'border-red-500/50', text: 'text-red-400', badge: 'bg-red-500' };
      case 'high': return { bg: 'bg-orange-500/20', border: 'border-orange-500/50', text: 'text-orange-400', badge: 'bg-orange-500' };
      case 'medium': return { bg: 'bg-yellow-500/20', border: 'border-yellow-500/50', text: 'text-yellow-400', badge: 'bg-yellow-500' };
      case 'low': return { bg: 'bg-blue-500/20', border: 'border-blue-500/50', text: 'text-blue-400', badge: 'bg-blue-500' };
      default: return { bg: 'bg-gray-500/20', border: 'border-gray-500/50', text: 'text-gray-400', badge: 'bg-gray-500' };
    }
  };

  const handleEditorDidMount = (editor: any, monaco: any) => {
    editorRef.current = editor;
    
    // 1. Draw the red squiggly lines
    const markers = vulnerabilities
      .filter(v => v.line_number !== null)
      .map(vuln => ({
        severity: monaco.MarkerSeverity.Error,
        message: `${vuln.title}\n\n${vuln.description}`, // Removed recommendation for cleaner tooltip
        startLineNumber: vuln.line_number,
        startColumn: 1,
        endLineNumber: vuln.line_number,
        endColumn: 1000,
        code: `VULN-${vuln.id}` // Tag it so we can hook into it
      }));
      
    monaco.editor.setModelMarkers(editor.getModel(), 'vulnerabilities', markers);

    // 2. ✅ GOD-TIER VS CODE UX: Register the Quick Fix Lightbulb Provider
    const codeActionProvider = monaco.languages.registerCodeActionProvider('*', {
      provideCodeActions: (model: any, range: any, context: any) => {
        const actions: any[] = [];
        
        context.markers.forEach((marker: any) => {
          // If this error is one of our vulnerabilities
          if (marker.code && marker.code.toString().startsWith('VULN-')) {
            const vulnId = parseInt(marker.code.replace('VULN-', ''));
            const vuln = vulnerabilitiesRef.current.find((v: any) => v.id === vulnId);
            
            if (vuln) {
              // Create a unique command inside the editor to execute our React function
              const commandId = editor.addCommand(0, () => {
                if (handleGetAISuggestionRef.current) {
                  handleGetAISuggestionRef.current(vuln);
                }
              });
              
              // Push the Lightbulb action
              actions.push({
                title: `✨ Auto-Fix: ${vuln.title}`,
                diagnostics: [marker],
                kind: 'quickfix',
                isPreferred: true, // Puts it at the top of the quick fix menu
                command: {
                  id: commandId,
                  title: 'Trigger AI Fix',
                  arguments: []
                }
              });
            }
          }
        });
        
        return { actions, dispose: () => {} };
      }
    });

    // Cleanup when editor unmounts
    editor.onDidDispose(() => {
      codeActionProvider.dispose();
    });
  };

  const handleDiffEditorDidMount = (editor: any) => {
    diffEditorRef.current = editor;
  };

  const scrollToLine = (lineNumber: number | null | undefined) => {
    if (!lineNumber) return;
    
    const targetEditor = showDiff ? diffEditorRef.current?.getModifiedEditor() : editorRef.current;
    if (targetEditor) {
      targetEditor.revealLineInCenter(lineNumber);
      targetEditor.setPosition({ lineNumber, column: 1 });
      targetEditor.focus();
    }
  };

  const handleGetAISuggestion = async (specificVuln?: Vulnerability) => {
    setFixingState(specificVuln ? specificVuln.id : 'all');
    setPreAIFixContent(modifiedContent);
    
    try {
      const token = localStorage.getItem('access_token');
      const vulnsToSend = specificVuln ? [specificVuln] : vulnerabilities;
      
      const response = await fetch(
        `${import.meta.env.VITE_API_URL}/api/v1/repositories/ai/fix-file`,
        {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            file_path: rawFilePath, 
            content: modifiedContent, 
            vulnerabilities: vulnsToSend.map(v => ({
              line: v.line_number,
              title: v.title,
              severity: v.severity,
            }))
          })
        }
      );
      
      const data = await response.json();
      if (data.fixed_content) {
        setModifiedContent(data.fixed_content);
        setShowDiff(true); 
        setIsReviewingAI(true); 
        
        const vulnList = vulnsToSend.map(v => `- Fixed ${v.title} (Line ${v.line_number || 'Global'})`).join('\n');
        setPrDescription(`Automated security fix generated by SecureThread AI.\n\n### Vulnerabilities Resolved:\n${vulnList}`);
      }
    } catch (error) {
      console.error('Error getting AI suggestion:', error);
      alert('Failed to get AI suggestion. Please try again.');
    } finally {
      setFixingState('idle');
    }
  };

  const handleAcceptAIFix = () => {
    setIsReviewingAI(false);
  };

  const handleRejectAIFix = () => {
    setModifiedContent(preAIFixContent); 
    setIsReviewingAI(false);
    setShowDiff(false); 
  };

  const openPRDrawerWithCheck = () => {
    let finalContent = modifiedContent;
    if (showDiff && diffEditorRef.current) {
      finalContent = diffEditorRef.current.getModifiedEditor().getValue();
    }

    if (finalContent === originalContent) {
      alert("No changes detected! Please manually edit the code or use 'Auto-Fix' before creating a Pull Request.");
      return;
    }

    setShowPRDrawer(true);
    setPrSuccessUrl(null);
  };

  const handleCreatePR = async () => {
    setIsSubmittingPR(true);
    try {
      let finalContent = modifiedContent;
      if (showDiff && diffEditorRef.current) {
        finalContent = diffEditorRef.current.getModifiedEditor().getValue();
      }

      const token = localStorage.getItem('access_token');
      const response = await fetch(
        `${import.meta.env.VITE_API_URL}/api/v1/repositories/${repositoryId}/create-pr`,
        {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            file_path: rawFilePath,
            new_content: finalContent,
            vulnerability_ids: vulnerabilities.map(v => v.id),
            pr_title: prTitle,
            pr_description: prDescription
          })
        }
      );
      
      const data = await response.json();
      if (data.pr_url) {
        window.open(data.pr_url, '_blank');
        setPrSuccessUrl(data.pr_url);
      } else {
        throw new Error(data.detail || "Failed to create PR");
      }
    } catch (error: any) {
      console.error('Error creating PR:', error);
      alert(error.message || 'Failed to create pull request');
    } finally {
      setIsSubmittingPR(false);
    }
  };

  if (missingTokenError) {
    return (
      <div className="h-screen flex flex-col bg-[#1E1E1E]">
        <div className="flex items-center justify-between px-6 py-4 bg-[#252526] border-b border-[#3E3E42]">
          <Button variant="ghost" onClick={() => navigate(`/projects/${repositoryId}`)} className="text-gray-400 hover:text-white hover:bg-[#3E3E42]">
            <ArrowLeft className="w-4 h-4 mr-2" /> Back to Project
          </Button>
        </div>
        <div className="flex-1 flex items-center justify-center p-6">
          <div className="max-w-md w-full bg-[#252526] border border-[#3E3E42] rounded-xl p-8 text-center shadow-2xl">
            <div className="w-20 h-20 bg-red-500/10 rounded-full flex items-center justify-center mx-auto mb-6">
              <Lock className="w-10 h-10 text-red-500" />
            </div>
            <h2 className="text-2xl font-bold text-white mb-3">Access Token Required</h2>
            <p className="text-gray-400 mb-8 leading-relaxed">
              We couldn't connect to your repository. You need to configure your Personal Access Token in the settings to view, edit, and commit code.
            </p>
            <Button 
              onClick={() => navigate('/settings')} 
              className="bg-purple-600 hover:bg-purple-700 text-white w-full py-6 text-lg rounded-lg shadow-lg shadow-purple-900/20"
            >
              Go to Integrations
            </Button>
          </div>
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="h-screen flex items-center justify-center bg-[#1E1E1E]">
        <div className="flex flex-col items-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-purple-500 mb-4"></div>
          <div className="text-gray-400">Loading editor environment...</div>
        </div>
      </div>
    );
  }

  return (
    <div className="h-screen flex flex-col bg-[#1E1E1E]">
      
      {/* Header */}
      <div className="flex items-center justify-between px-6 py-4 bg-[#252526] border-b border-[#3E3E42]">
        <div className="flex items-center space-x-6 overflow-hidden">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate(`/projects/${repositoryId}`)}
            className="text-gray-400 hover:text-white hover:bg-[#3E3E42] flex-shrink-0"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back
          </Button>
          
          <div className="min-w-0 flex-1">
            <div className="flex items-center text-sm font-semibold text-gray-100 mb-1">
              <FileCode2 className="w-4 h-4 mr-2 text-purple-400 flex-shrink-0" />
              <span className="truncate">{fileName}</span>
              {showDiff && <Badge className="ml-3 bg-purple-500/20 text-purple-400 border border-purple-500/50 flex-shrink-0">Reviewing Changes</Badge>}
            </div>
            
            <div className="flex items-center text-xs text-gray-500 font-mono truncate">
              {pathParts.map((part, idx) => (
                <React.Fragment key={idx}>
                  <span className="hover:text-gray-300 transition-colors cursor-default">{part}</span>
                  <ChevronRight className="w-3 h-3 mx-1 opacity-50 flex-shrink-0" />
                </React.Fragment>
              ))}
              <span className="text-gray-300 truncate">{fileName}</span>
            </div>
          </div>
        </div>

        <div className="flex items-center space-x-3 flex-shrink-0">
          
          <div className="flex bg-[#181818] rounded-lg p-1 border border-[#3E3E42] shadow-inner">
            <button 
              onClick={() => setShowDiff(false)}
              disabled={isReviewingAI} 
              className={`px-4 py-1.5 text-xs font-medium rounded-md transition-all duration-200 ${!showDiff ? 'bg-[#3E3E42] text-white shadow-sm' : 'text-gray-400 hover:text-gray-200 disabled:opacity-50'}`}
            >
              Standard
            </button>
            <button 
              onClick={() => setShowDiff(true)}
              disabled={isReviewingAI}
              className={`px-4 py-1.5 text-xs font-medium rounded-md transition-all duration-200 ${showDiff ? 'bg-purple-600 text-white shadow-sm' : 'text-gray-400 hover:text-gray-200 disabled:opacity-50'}`}
            >
              Split Diff
            </button>
          </div>

          <Button
            variant="outline"
            onClick={() => handleGetAISuggestion()}
            disabled={fixingState !== 'idle' || isReviewingAI || vulnerabilities.length === 0}
            className="border-purple-500/50 text-purple-400 bg-purple-500/10 hover:bg-purple-500 hover:text-white transition-all duration-300 ml-2"
          >
            {fixingState === 'all' ? (
              <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2" />
            ) : (
              <Sparkles className="w-4 h-4 mr-2" />
            )}
            {fixingState === 'all' ? 'Fixing...' : 'Auto-Fix All'}
          </Button>

          <Button
            onClick={openPRDrawerWithCheck}
            disabled={isReviewingAI}
            className="bg-green-600 hover:bg-green-500 text-white shadow-lg shadow-green-900/20 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <GitPullRequest className="w-4 h-4 mr-2" />
            Commit & PR
          </Button>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 flex overflow-hidden relative">
        
        {/* Editor Area with Review Banner */}
        <div className="flex-1 flex flex-col border-r border-[#3E3E42]">
          
          {isReviewingAI && (
            <div className="bg-purple-900/30 border-b border-purple-500/50 p-3 flex items-center justify-between shrink-0 z-10 shadow-md">
              <div className="flex items-center text-purple-200 text-sm font-medium">
                <Sparkles className="w-4 h-4 mr-2 text-purple-400 animate-pulse" />
                AI Fix Proposed. Please review the highlighted changes below.
              </div>
              <div className="flex items-center space-x-3">
                <Button 
                  size="sm" 
                  variant="outline" 
                  onClick={handleRejectAIFix}
                  className="border-red-500/50 text-red-400 hover:bg-red-500/20 hover:text-red-300 h-8"
                >
                  <XCircle className="w-3.5 h-3.5 mr-1.5" />
                  Discard
                </Button>
                <Button 
                  size="sm" 
                  onClick={handleAcceptAIFix}
                  className="bg-green-600 hover:bg-green-500 text-white h-8 shadow-sm"
                >
                  <Check className="w-3.5 h-3.5 mr-1.5" />
                  Accept Fix
                </Button>
              </div>
            </div>
          )}

          <div className="flex-1 relative">
            {showDiff ? (
              <DiffEditor
                height="100%"
                language={language}
                original={originalContent}
                modified={modifiedContent}
                theme="vs-dark"
                onMount={handleDiffEditorDidMount}
                options={{
                  renderSideBySide: true,
                  minimap: { enabled: false },
                  fontSize: 14,
                  fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
                  ignoreTrimWhitespace: false,
                  originalEditable: false,
                  automaticLayout: true,
                  readOnly: isReviewingAI 
                }}
              />
            ) : (
              <Editor
                height="100%"
                language={language}
                value={modifiedContent}
                onChange={(value) => setModifiedContent(value || '')}
                onMount={handleEditorDidMount}
                theme="vs-dark"
                options={{
                  minimap: { enabled: true },
                  fontSize: 14,
                  fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
                  lineNumbers: 'on',
                  glyphMargin: true,
                  scrollBeyondLastLine: false,
                  automaticLayout: true,
                }}
              />
            )}
          </div>
        </div>

        {/* ✅ CLEANED Vulnerabilities Sidebar */}
        <div className="w-96 bg-[#252526] flex flex-col z-10 shadow-[-10px_0_15px_rgba(0,0,0,0.2)]">
          <div className="p-4 border-b border-[#3E3E42] bg-[#1E1E1E]">
            <h3 className="text-gray-100 font-semibold flex items-center text-sm">
              <AlertCircle className="w-4 h-4 mr-2 text-red-500" />
              Detected Vulnerabilities ({vulnerabilities.length})
            </h3>
          </div>
          
          <div className="flex-1 overflow-y-auto p-4 space-y-4 custom-scrollbar">
            {vulnerabilities.map((vuln) => {
              const colors = getSeverityColor(vuln.severity);
              
              return (
                <div 
                  key={vuln.id} 
                  onClick={() => scrollToLine(vuln.line_number)}
                  className={`p-4 bg-[#2D2D30] rounded-xl border transition-all cursor-pointer group ${isReviewingAI ? 'opacity-50 pointer-events-none border-[#3E3E42]' : 'border-[#3E3E42] hover:border-purple-500/50 hover:bg-[#323235]'}`}
                >
                  <div className="flex items-center justify-between mb-3">
                    <Badge className={`${colors.badge} text-white text-xs px-2.5 py-0.5 border-none font-semibold uppercase tracking-wider`}>
                      {vuln.severity}
                    </Badge>
                    <span className="text-xs text-gray-400 font-mono bg-[#1E1E1E] px-2.5 py-1 rounded-md border border-[#3E3E42] group-hover:border-purple-500/30 transition-colors">
                      {vuln.line_number ? `Line ${vuln.line_number}` : 'Global File'}
                    </span>
                  </div>
                  
                  <h4 className="text-sm font-semibold text-gray-100 mb-2 leading-snug">
                    {vuln.title}
                  </h4>
                  
                  <p className="text-xs text-gray-400 leading-relaxed m-0">
                    {vuln.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>

        {/* PR Submission Drawer */}
        {showPRDrawer && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 pointer-events-none">
            
            <div 
              className="absolute inset-0 bg-black/60 backdrop-blur-sm pointer-events-auto transition-opacity"
              onClick={() => !isSubmittingPR && !prSuccessUrl && setShowPRDrawer(false)}
            />
            
            <div className="relative w-full max-w-2xl bg-[#252526] border border-[#3E3E42] rounded-xl shadow-2xl pointer-events-auto overflow-hidden">
              
              {prSuccessUrl ? (
                <div className="p-8 text-center flex flex-col items-center justify-center">
                  <div className="w-16 h-16 bg-green-500/20 rounded-full flex items-center justify-center mb-4">
                    <CheckCircle className="w-8 h-8 text-green-500" />
                  </div>
                  <h2 className="text-2xl font-bold text-white mb-2">Pull Request Created!</h2>
                  <p className="text-gray-400 mb-8">Your security fixes have been successfully submitted to your GitHub repository.</p>
                  
                  <div className="flex space-x-4">
                    <Button 
                      onClick={() => navigate(`/projects/${repositoryId}`)} 
                      className="bg-[#3E3E42] hover:bg-[#4E4E52] text-white min-w-[150px]"
                    >
                      Return to Project
                    </Button>
                    <Button 
                      onClick={() => window.open(prSuccessUrl, '_blank')} 
                      className="bg-green-600 hover:bg-green-500 text-white min-w-[150px]"
                    >
                      View on GitHub
                    </Button>
                  </div>
                </div>
              ) : (
                <>
                  <div className="flex items-center justify-between p-5 border-b border-[#3E3E42]">
                    <h2 className="text-lg font-semibold text-white flex items-center">
                      <GitPullRequest className="w-5 h-5 mr-2 text-green-500" />
                      Ready to ship your fixes?
                    </h2>
                    <button onClick={() => setShowPRDrawer(false)} className="text-gray-400 hover:text-white bg-[#1E1E1E] p-1.5 rounded-md border border-[#3E3E42]">
                      <X className="w-4 h-4" />
                    </button>
                  </div>
                  
                  <div className="p-6 space-y-5">
                    <div>
                      <label className="block text-sm font-medium text-gray-300 mb-2">Pull Request Title</label>
                      <Input 
                        value={prTitle}
                        onChange={(e) => setPrTitle(e.target.value)}
                        className="bg-[#1E1E1E] border-[#3E3E42] text-gray-100 focus:border-green-500 focus:ring-1 focus:ring-green-500 font-medium"
                      />
                    </div>
                    
                    <div>
                      <label className="block text-sm font-medium text-gray-300 mb-2">Description</label>
                      <Textarea 
                        value={prDescription}
                        onChange={(e) => setPrDescription(e.target.value)}
                        rows={6}
                        className="bg-[#1E1E1E] border-[#3E3E42] text-gray-300 resize-none focus:border-green-500 focus:ring-1 focus:ring-green-500 font-mono text-sm leading-relaxed"
                      />
                    </div>
                    
                    <div className="bg-blue-500/10 border border-blue-500/20 rounded-xl p-4 flex items-start">
                      <AlertCircle className="w-5 h-5 text-blue-400 mr-3 flex-shrink-0 mt-0.5" />
                      <div className="text-sm text-blue-200 leading-relaxed">
                        This will create a new branch containing your security fixes and automatically open a Pull Request against the default branch on GitHub.
                      </div>
                    </div>

                    <div className="flex justify-end space-x-3 pt-4 border-t border-[#3E3E42] mt-6">
                      <Button variant="ghost" onClick={() => setShowPRDrawer(false)} className="text-gray-300 hover:text-white hover:bg-[#3E3E42]">
                        Cancel
                      </Button>
                      <Button 
                        onClick={handleCreatePR} 
                        disabled={isSubmittingPR}
                        className="bg-green-600 hover:bg-green-500 text-white min-w-[160px] shadow-lg shadow-green-900/20"
                      >
                        {isSubmittingPR ? (
                          <div className="flex items-center">
                            <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin mr-2" />
                            Creating PR...
                          </div>
                        ) : (
                          <span className="flex items-center">
                            <GitPullRequest className="w-4 h-4 mr-2" />
                            Create Pull Request
                          </span>
                        )}
                      </Button>
                    </div>
                  </div>
                </>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default FileEditor;